#!/bin/sh

set -e

# Steps:

# - Stash (any) changes so we can switch branches later

git stash


# - Generate metadata

mkdir -p metadata
./make-image-metadata
./git-metadata


# - Build the site

stack run -- clean
stack run -- build


# - Switch branches

git checkout gh-pages


# - Move down a directory, as we're in 'src' presently.

cd ..

# - Copy the "_site" to the root, but don't delete things we want. (i.e. the
#   things that are peristed due to branch switches; those things in the
#   gitignore file.)

rsync -a --filter='P src/'            \
         --filter='P .git/'           \
         --filter='P .gitignore'      \
         --filter='P .README.md'      \
         --filter='P .nojekyll'       \
         --filter='P metadata'        \
         --filter='P CNAME'           \
         --delete-excluded            \
         src/_site/ .


# - Add commit and push

git add -A
git commit -m "Update." || true
git push --force-with-lease origin gh-pages


# - Bring everything back

git checkout main
git stash pop
